# **Actividad 1: Carga y creación de Dataset**

En este notebook se construye el flujo de trabajo completo para la primera parte del proyecto carga y creación de el dataset llamado "California housing" o en español "Viviendas de California".

### **1. Se prepara el entorno e importa la clase de carga**

In [1]:
import sys
from pathlib import Path

ROOT = Path.cwd().resolve()
while ROOT != ROOT.parent and not (ROOT / "src" / "clases").exists():
    ROOT = ROOT.parent

sys.path.insert(0, str(ROOT / "src"))

from clases import HFDatasetLoader
from clases import Reportes

/home/runner/work/Machine-Learning/Machine-Learning/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

### **2. Se configura el dataset y la salida**

In [2]:
loader = HFDatasetLoader( dataset_name="BrianSuToronto/california_housing", split="train", filename= "data/california_housing.csv")

### **3. Se descarga el dataset y se crea el DataFrame**

In [3]:
df = loader.load()
df.head(3)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Generating train split:   0%|          | 0/20640 [00:00<?, ? examples/s]

Generating train split: 100%|██████████| 20640/20640 [00:00<00:00, 654196.18 examples/s]

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521

### **4. Revisamos la estructura del DataFrame**

In [4]:
print(f"Filas: {len(df)}")
print(f"Columnas: {len(df.columns)}")
df.info()

Filas: 20640
Columnas: 9
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   MedInc       20640 non-null  float64
 1   HouseAge     20640 non-null  float64
 2   AveRooms     20640 non-null  float64
 3   AveBedrms    20640 non-null  float64
 4   Population   20640 non-null  float64
 5   AveOccup     20640 non-null  float64
 6   Latitude     20640 non-null  float64
 7   Longitude    20640 non-null  float64
 8   MedHouseVal  20640 non-null  float64
dtypes: float64(9)
memory usage: 1.4 MB

### **5. Apartir de aquí hacemos las transformaciones mínimas**

#### **Tranformación 1 (Renombrado)**

In [5]:
# Mostramos los nombres originales de las columnas
print(df.columns)

Index(['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup',
       'Latitude', 'Longitude', 'MedHouseVal'],
      dtype='object')

In [6]:
# Renombramos las columnas
df_transformado = df.rename(columns={
    "MedInc": "Ingreso_mediano",
    "HouseAge": "Edad_vivienda",
    "AveRooms": "Promedio_habitaciones",
    "AveBedrms": "Promedio_dormitorio_hogar",
    "Population": "Poblacion",
    "AveOccup": "Promedio_ocupacion",
    "Latitude": "Latitud",
    "Longitude": "Longitud",
    "MedHouseVal": "Valor_mediano_vivienda"
})

#### **Transformación 2 (Filtrado)**

In [7]:
df_t2 = df_transformado[df_transformado["Edad_vivienda"] > 20]

#### **Transformación 3 (Seleccionado)**

In [8]:
df_t3 = df_t2[[
    "Ingreso_mediano",
    "Edad_vivienda",
    "Promedio_habitaciones",
    "Poblacion",
    "Valor_mediano_vivienda",
]]

#### **Transformación 4 (Columna nueva)**

In [9]:
df_t4 = df_t3.assign(Valor_en_dolares=df_t3["Valor_mediano_vivienda"] * 100000)

### **6. Resultados y explicaciones de las transformaciones**

**Resultados por filas y columas**

In [10]:
# Se muestran los resultados por filas y columnas
print("Se muestran los resultados por filas y columnas")
print("Original:     ", df.shape)
print("Renombrado:   ", df_transformado.shape)
print("Filtrado:     ", df_t2.shape)
print("Seleccionado: ", df_t3.shape)
print("Con columna:  ", df_t4.shape)
print(df_t4.columns.tolist())

Se muestran los resultados por filas y columnas
Original:      (20640, 9)
Renombrado:    (20640, 9)
Filtrado:      (14347, 9)
Seleccionado:  (14347, 5)
Con columna:   (14347, 6)
['Ingreso_mediano', 'Edad_vivienda', 'Promedio_habitaciones', 'Poblacion', 'Valor_mediano_vivienda', 'Valor_en_dolares']

**Resultados de cada transformación**

In [11]:
# Importamos display para mostrar los resultados de cada transformación 
from IPython.display import display
# Nombres de las columnas originales
print("Original (nombres en inglés):")
display(df.head())
# Columnas renombradas
print("Renombrado (nombres en español):")
display(df_transformado.head())
# Filtrado 
print("Filtrado (Edad_vivienda > 20):")
display(df_t2.head())
# Seleccionado 
print("Seleccionado (5 columnas):")
display(df_t3.head())
# Nueva columna
print("Con la nueva columna Valor_en_dolares:")
display(df_t4.head())

Original (nombres en inglés):

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422

Renombrado (nombres en español):

,Ingreso_mediano,Edad_vivienda,Promedio_habitaciones,Promedio_dormitorio_hogar,Poblacion,Promedio_ocupacion,Latitud,Longitud,Valor_mediano_vivienda
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422

Filtrado (Edad_vivienda > 20):

,Ingreso_mediano,Edad_vivienda,Promedio_habitaciones,Promedio_dormitorio_hogar,Poblacion,Promedio_ocupacion,Latitud,Longitud,Valor_mediano_vivienda
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422

Seleccionado (5 columnas):

,Ingreso_mediano,Edad_vivienda,Promedio_habitaciones,Poblacion,Valor_mediano_vivienda
0,8.3252,41.0,6.984127,322.0,4.526
1,8.3014,21.0,6.238137,2401.0,3.585
2,7.2574,52.0,8.288136,496.0,3.521
3,5.6431,52.0,5.817352,558.0,3.413
4,3.8462,52.0,6.281853,565.0,3.422

Con la nueva columna Valor_en_dolares:

,Ingreso_mediano,Edad_vivienda,Promedio_habitaciones,Poblacion,Valor_mediano_vivienda,Valor_en_dolares
0,8.3252,41.0,6.984127,322.0,4.526,452600.0
1,8.3014,21.0,6.238137,2401.0,3.585,358500.0
2,7.2574,52.0,8.288136,496.0,3.521,352100.0
3,5.6431,52.0,5.817352,558.0,3.413,341300.0
4,3.8462,52.0,6.281853,565.0,3.422,342200.0

#### **Explicación 1 (Renombrado)**
Se usó `DataFrame.rename()` para cambiar los nombres de las columnas de inglés a español (por ejemplo, `MedInc` pasó a `Ingreso_mediano`), porque los nombres en español son más fáciles de entender y tienen una mejor interpretación en todo el análisis, el resultado es el DataFrame conservando las mismas 20640 filas y 9 columnas, y solo cambiaron los nombres. El DataFrame original (`df`) no se modificó, porque `rename()` devuelve uno nuevo, guardado en `df_transformado`.

#### **Explicación 2 (Filtrado)**
Se filtró `df_transformado` con la condición `Edad_vivienda > 20`, y el resultado se guardó en `df_t2`así se analizan solo las zonas con viviendas de más de 20 años de antigüedad mediana y el DataFrame pasó de 20640 a 14347 filas y mantiene las 9 columnas. Las filas que no cumplían la condición se descartaron.

#### **Explicación 3 (Seleccionado)**
A partir de `df_t2` se seleccionaron cinco columnas (`Ingreso_mediano`, `Edad_vivienda`, `Promedio_habitaciones`, `Poblacion` y `Valor_mediano_vivienda`), y el resultado se guardó en `df_t3`, se conservan solo las variables más relevantes y se descartan las demás para simplificar el análisis y el número de filas se mantiene en 14347 y las columnas bajaron de 9 a 5.

#### **Explicación 4 (Columna nueva)**
Con `assign()` se creó la columna `Valor_en_dolares`, que multiplica `Valor_mediano_vivienda` por 100.000. El resultado se guardó en `df_t4`, porque en este dataset el valor mediano de la vivienda está expresado en cientos de miles de dólares, por lo que la nueva columna lo muestra en dólares y es más fácil de interpretar (por ejemplo, 3.5 equivale a 350.000 USD) y el DataFrame mantiene 14347 filas y pasó de 5 a 6 columnas.

#### **Resultado final y reporte**

El DataFrame final (`df_t4`) tiene 14347 filas y 6 columnas. Este DataFrame transformado se pasa a la clase `Reportes`, que generó el archivo `.txt` con el resumen: filas, columnas, duplicados, tipos de dato, valores nulos y estadísticas numéricas. Por eso, el archivo corresponde a los datos transformados y no a los originales.

### **7. Generamos el reporte**

In [12]:
reportes = Reportes()
texto = reportes.generar_reporte(df_t4)

print(texto)

REPORTE DEL DATAFRAME
============================================================
Filas: 14347
Columnas: 6
Duplicados: 0

Columnas y tipos:
- Ingreso_mediano: float64
- Edad_vivienda: float64
- Promedio_habitaciones: float64
- Poblacion: float64
- Valor_mediano_vivienda: float64
- Valor_en_dolares: float64

Valores nulos por columna:
- Ingreso_mediano: 0
- Edad_vivienda: 0
- Promedio_habitaciones: 0
- Poblacion: 0
- Valor_mediano_vivienda: 0
- Valor_en_dolares: 0

Estadísticas numéricas:
       Ingreso_mediano  Edad_vivienda  Promedio_habitaciones  Poblacion  Valor_mediano_vivienda  Valor_en_dolares
count        14347.000      14347.000              14347.000  14347.000               14347.000         14347.000
mean             3.750         35.142                  5.201   1258.586                   2.127        212737.785
std              1.889          8.901                  2.263    799.315                   1.203        120256.840
min              0.500         21.000                  0.846      5.000                   0.150         14999.000
25%              2.484         28.000                  4.337    759.500                   1.208        120800.000
50%              3.400         34.000                  5.069   1091.000                   1.849        184900.000
75%              4.562         41.000                  5.820   1553.500                   2.722        272200.000
max             15.000         52.000                141.909  12427.000                   5.000        500001.000

### **8.Imprimimos el reporte**

In [13]:
reportes = Reportes()
reportes.imprimir_reporte(df_t4)                        # muestra el resultado

REPORTE DEL DATAFRAME
============================================================
Filas: 14347
Columnas: 6
Duplicados: 0

Columnas y tipos:
- Ingreso_mediano: float64
- Edad_vivienda: float64
- Promedio_habitaciones: float64
- Poblacion: float64
- Valor_mediano_vivienda: float64
- Valor_en_dolares: float64

Valores nulos por columna:
- Ingreso_mediano: 0
- Edad_vivienda: 0
- Promedio_habitaciones: 0
- Poblacion: 0
- Valor_mediano_vivienda: 0
- Valor_en_dolares: 0

Estadísticas numéricas:
       Ingreso_mediano  Edad_vivienda  Promedio_habitaciones  Poblacion  Valor_mediano_vivienda  Valor_en_dolares
count        14347.000      14347.000              14347.000  14347.000               14347.000         14347.000
mean             3.750         35.142                  5.201   1258.586                   2.127        212737.785
std              1.889          8.901                  2.263    799.315                   1.203        120256.840
min              0.500         21.000                  0.846      5.000                   0.150         14999.000
25%              2.484         28.000                  4.337    759.500                   1.208        120800.000
50%              3.400         34.000                  5.069   1091.000                   1.849        184900.000
75%              4.562         41.000                  5.820   1553.500                   2.722        272200.000
max             15.000         52.000                141.909  12427.000                   5.000        500001.000

### **9. Guardamos el reporte en el .txt**

In [ ]:
ruta = reportes.guardar_reporte(
    df_t4,"reportes/entrega_1/california_housing.txt",
) 
print(f"El reporte ha sido guardado en: {ruta}")

El reporte ha sido guardado en: reportes/california_housing.txt